dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.4.1
compiler:
  solc:
    remappings:
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.4.1'
networks:
  default: development
  kovan:
    weth_token: '0xd0a1e359811322d97991e03f863a0c30c2cf029c' 
    dao_token: '0xA64F78b1C7fef0FD9Bb22be08c7b0733dc91A86f'
  my-mainnet-fork:
    weth_token: '0xd0a1e359811322d97991e03f863a0c30c2cf029c' 
    dao_token: '0xA64F78b1C7fef0FD9Bb22be08c7b0733dc91A86f'
dotenv: .env
wallets:
  from_key: ${PRIVATE_KEY}